### ISSUE TITLE
predicativize the framework

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/type-refinements-for-the-working-class#10]
@freebroccolo I think it might be a good idea to adjust the formulation to be predicative—but I don't want to commit to a bunch of scary stuff to get there, since category theory isn't the point of this paper (nor set theory)

[submitted too soon, see impending comment for more detail]

**Comment by jonsterling** [comment]
[Submitted too soon]

So, I'm wondering if you think there's a sensible way for us to just say that by `SET` we mean a category of classes (large sets, I guess?), and by presheaf we mean a contravariant functor to this category. Then, our presheaf category is a `PWM pretopos` equipped with a notion of small maps, and a small presheaf `F` is one such that the map `F -> 1` is a small map.

In such a setting, we have a small power object `P_s(X)` which can be used on any small object/presheaf `X`. So, it should be pretty easy to just replace all incidental uses of the subobject classifier with a use of the small power object.

Does this make sense? I guess what I'm really wondering is whether we can get away with just stipulating this machinery without going into too much detail, since I really don't want to get mired in "foundations".

**Comment by jonsterling** [comment]
@freebroccolo I was just looking over Gambino's thesis "Sheaf interpretations of generalized predicative intuitionistic systems", where he defines a lot of the category-of-classes machinery, and it looks like the situation is even better than I thought.

We can always form the class of subsets of a set, and likewise, we can even form the class of subsets of a class. We do not ever need the set of subsets or class of subclasses for anything. So I think it should be quite straightforward to make everything predicative.

**Comment by freebroccolo** [comment]
Wow, this is great. I haven't read the Gambino thesis yet (added it to my reading list) but if it's straightforward to present things in a predicative fashion that would be make me happy (even though it was still okay before, I think).

**Comment by jonsterling** [comment]
@freebroccolo Cool, glad you are happy with it!

Yeah, it seems like the difficulty with the predicative topoi lies in defining "the" predicative analogue to the elementary topos—whereas, we can take advantage of the fact that we were in a category of presheaves anyway, so making it predicative is exactly as simple as it is in type theory.
