### ISSUE TITLE
discuss modalities

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/type-refinements-for-the-working-class#13]
Nuprl has a type called something like `a # A`, which contains the elements of `A` which do not mention the atom/symbol `a`. In our setting, this is clearly a modality. We can also add other modalities, like necessity `[Y] A` (elements of `A` that use only the atoms in `Y`); I'm not sure what modal possibility would mean (@freebroccolo, any ideas?).

~~What would be super cool is if we could show a way to treat these modalities semantically using Lawvere-Tierney local operators (i.e. natural transformations `Ω -> Ω`, subject to a few laws).~~ Hmm, I don't think that will work.

By the way, a lot of this paper will likely have to be trimmed out, but I'd like to develop it as broadly as possible before doing so; this way, we'll be more likely to run into any possible problems prior to submission rather than after, and we'll also have a better idea of the space for future work on the topic.

**Comment by freebroccolo** [comment]
Is the nuprl type for that mentioned somewhere? Don't think I've seen that before. I'm not sure about modal possibility either but this seems like the sort of thing someone must have talked about somewhere but maybe not quite in these terms. Do you have an idea of how such a thing would be used?

I agree about the breadth and scope btw. Working out a lot of the details seems good to me even if it does mean stuff will need to be trimmed back eventually. If there's enough material, maybe it could go into another paper or something.

**Comment by jonsterling** [comment]
@freebroccolo The type is discussed in http://www.nuprl.org/documents/Bickford/Authentication.pdf, written as `M || a`, which means "`a` is fresh in `M`"; the modality I mentioned then could be formulated using the set comprehension `{x : S | (x || a)}` or something.

**Comment by jonsterling** [comment]
It will not be possible to express a useful notion of "nominal possibility" as a modal operator on refinements, because the presuppositions cannot work out. That is, for `Y || M = N in φ`, it is presupposed that `M,N` be terms at `Y`; so, even if we gave the meaning of `Y || M = N in <>φ` as something like "There exists a `ρ : Y -> Y'` such that `Y' || M.ρ = N.ρ in φ.ρ`, this would be pretty much trivial / useless, since we could never use it for an `M,N` which actually use more symbols than `Y`. The best it could do would be to capture a renaming that only permutes or renames symbols, but does not extend them, but that sounds pretty useless.

I'm not sure that I will worry too much about this, given that I don't really have a use for possibility at this time anyway.

**Comment by jonsterling** [comment]
However, it would be possible to do this in an individual signature by adding a family of operators like `poss[σ*] : ({σ*}[]. τ)τ`.
