### ISSUE TITLE
give a small multi-sorted computational type theory

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/type-refinements-for-the-working-class#3]
This will make a lovely example. We'll start with a multi-sorted version of Howe's computational approximation & equivalence, and then define judgments that express properties of refinements, including:

- the refinement respects computation; all refinements that we will use in CTT must fall in this category
- the refinement is determined by its values (i.e. it's a VPER); all the refinements for ITT fall in this category, but in CTT we can define refinements such as `Base(τ)`, `Top(τ)`, and `Partial(φ)` which are not VPERs.

@jozefg Do you have a reference for doing the Howe stuff for many-sorted calculi?

**Comment by jozefg** [comment]
I don't off the top of my head but I'll certainly poke around. Howe's original work was based on a primitive ABT like definition though so it might not be too complicated to just port the original paper to this new setting.. I may give that a try tomorrow.

**Comment by jonsterling** [comment]
This will also be a nice place to show how certain things you might naïvely expect to hold do not; for instance, it is not the case that `x:ψ != x \in Base(τ)` even if `ψ refines τ`. This really confused me, and was the source of a very serious inconsistency in JonPRL which either @vrahli or @jozefg noticed; well, coming from a background in formal type theory, I had expected this to be true, but it is of course false, since if `ψ`'s equality is courser than Howe, you could use it to refute functionality.

Anyway, however, when you take the sequent and expand its according to the meaning explanation, it is clear that it is potentially false! The meaning of the judgment is:

````
|(𝔪:[].τ, 𝔫:[].τ) 𝔪[] ~[τ]~ 𝔫[]   (𝔪[] = 𝔫[] in ψ)
````

And that's manifestly not the case unless `ψ`'s equality is merely computational.

**Comment by jonsterling** [comment]
@jozefg Cool. If you do get a chance to look into that, let me know! :) And if there's any work that needs to be done for it to work, would be happy to collaborate.

**Comment by jonsterling** [comment]
I found a reference for generalizing Howe's method to a typed setting; Gordon's "Bisimilarity as a Theory of Functional Programming" (1995).

I don't think we actually need to prove that bisimulation is a congruence in this paper, as we can simply cite the result and call it good.

**Comment by jozefg** [comment]
@jonsterling Ah but what fun is that :) it'd be a really good way to kick the tires of a mechanized formulation of this if one was made.

**Comment by jonsterling** [comment]
Heh... Well, it would be fun! If you'd like to join in, you are welcome! I have a feeling we may not mechanize the machinery in this paper, though as you can see from the formulation of the ambient logical framework, I am trying to be as precise as possible so that we (or someone) may mechanize it easily.

**Comment by jonsterling** [comment]
OK, I think I've fixed up what I wrote last night after a few beers to the point that it is actually correct.
