### ISSUE TITLE
consider switching semantic universe to Set^Sctx

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/type-refinements-for-the-working-class#4]
My perspective was initially that it would be nice to develop the ambient logical framework abstractly such that it could be deployed with whatever notion of epistemic change that the user wished, so long as it supported a notion of renaming-of-symbol-parameters in derivations.

However, the only part of this which is actually useful in the current development is renaming of parameters; therefore, it feels like the rest of the machinery is a bit hard to motivate and might be puzzling to a reader. So, I'm proposing that we simplify this and just let `J := Set^SCtx`.

@freebroccolo What do you think about this?

**Comment by freebroccolo** [comment]
Well, this seems reasonable to me. I sort of agree that the extra generality may not be warranted in this case even though it's still interesting and may be worth exploring if we can find a compelling case for it.
